Postgrado en Análisis y Predicción de Datos  
IIO - Universidad Galileo  
Marzo, 2021  
 
<H1><center> Laboratorio #4 - Data Wrangling with Pandas</center></H1>

### Denis Alexis Solis Arroyo
### 20 000 143

## Instrucciones
En este laboratorio debe poner en práctica sus conocimientos sobre la librería Pandas y utilizarlo para manipular datos. El departamento de Marketing necesita analizar el comportamiento de las cuentas de varias cuentas de Instagram para entender a la compentencia y desarrollar una estrategia para mejorar los indicadores de la empresa para la que usted trabaja. En la carpeta _data_ se encuentran varios archivos, cada uno de los archivos contiene información sobre los posts de Instagram de una cuenta diferente. A lo largo de este Jupyter Notebook encontrará varias instrucciones indicando los pasos que debe realizar y los resultados esperados para completar su práctica. Debe trabajar en este mismo Notebook lo que se le solicita y luego cargar el archivo _laboratorio4.ipynb_ al GES, no modifique el nombre del archivo.

Si desea saber mas sobre como generar estos archivos puede visitar https://milaronix.com/2021/01/16/como-analizar-perfiles-de-instagram-utilizando-python/

In [2]:
#Estas son las únicas 2 librerías necesarias para este laboratorio. NO importe librerías adicionales. Si importa librerías adicionales será penalizado.
import pandas as pd
import os

## Cargando los archivos y completando data faltante

Cree un DataFrame llamado 'data' que contenga la información de todos los archivos dentro de la carpeta 'data'. Considere que al cargar cada uno de los archivos puede tener errores en la columna _username_ , cada archivo tiene un solo valor de _username_ entonces puede rellenar los errores con el valor correspondiente de cada archivo.

In [73]:
del data1
del data

In [74]:
#lea todos los archivos dentro de la carpeta data, luego cree un DataFrame consolidado llamado data
files = [file for file in os.listdir("./data")]
data = pd.DataFrame()
data1 = pd.DataFrame()
files

['buthewestie.txt',
 'dechuchos.txt',
 'guatemalapetfriendly.txt',
 'potter_cm.txt',
 'viajaconorus.txt']

In [75]:
for file in files:
    df = pd.read_csv("./data/" + file, sep = "|")
    data1 = pd.concat([data1, df])

In [76]:
data = data1
data

,Unnamed: 0,csrf_token,viewer,viewer_id,country_code,language_code,locale,device_id,browser_push_pub_key,key_id,...,viewer_has_saved_to_collection,viewer_in_photo_of_you,viewer_can_reshare,video_url,has_audio,video_view_count,username,full_name,upload_date,hashtags
0,0,D6iS7WnSFbhB9ZUFt5nWK51xdDegcZ6V,NaN,NaN,GT,en,en_US,D4425F91-940E-4EE7-8FAA-4E1AAA1A8B58,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-21 09:22:24,[]
1,1,n9cW3xMiT311ZhtAfXYnEYO9dRBGkbhE,NaN,NaN,GT,en,en_US,D4EBBE02-4EF2-46E4-ACA7-4F8908A0C0AF,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-20 09:32:18,[]
2,2,Y5WDcpqc8y0rsED1yI8YciJSgEqLJ9bT,NaN,NaN,GT,en,en_US,251B69CB-92EE-4D3A-B536-72AD356D98D8,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-16 09:28:28,['dogapproved']
3,3,5vFgXtmB2ihqowxoeLeVKvWA8UrpxAsa,NaN,NaN,GT,en,en_US,A0334128-ADCC-4A0F-8FD9-F27024D2BC57,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-13 14:57:03,"['OliyBu', 'ThiagoyBu', 'OliThiagoyBu']"
4,4,F4ejlkqj0IhfwjCDxNAdffQCjBci05NN,NaN,NaN,GT,en,en_US,4C162E02-7158-4F01-AE88-7A3FC33167EE,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-07 11:44:15,"['christmaspresent', 'bestchristmaspresent', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,282,n4Op0SpSdON8Alm73sklKsFtMSFajndb,NaN,NaN,GT,en,en_US,24F51DB7-3445-4134-840A-7F192ACEABC1,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,viajaconorus,ORUS 🐶,2018-03-19 20:45:33,"['viajaconnosotrosgt', 'mascota', 'perrito', '..."
283,283,oA6HHMM4mtARcUGfY1t1bbDNc81Q5t11,NaN,NaN,GT,en,en_US,B78146C2-D168-4D90-B0A6-EAA209EC5F62,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,viajaconorus,ORUS 🐶,2018-03-17 11:30:10,"['viajaconnosotrosgt', 'mascota', 'cachorro', ..."
284,284,Teg45mwLe9IFd9PpUI5eANuxJ4apJ6ii,NaN,NaN,GT,en,en_US,62F229B7-FC8B-4252-8C15-6BA598AFA910,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,viajaconorus,ORUS 🐶,2018-03-15 09:53:09,"['viajaconnosotrosgt', 'viajero', 'playa', 'ma..."
285,285,j5KK3RgXxlVqWCx26IuPndKI6lUOixw2,NaN,NaN,GT,en,en_US,8B45189C-6935-46D6-B4E2-4C3F994665B5,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,viajaconorus,ORUS 🐶,2018-03-14 13:16:33,"['viajaconnosotrosgt', 'instadog', 'instaguate..."
286,286,RaCqworpc7ms10NX7mVJHSDvLf1egd8R,NaN,NaN,GT,en,en_US,2CB5958D-4D52-4F66-A15D-8D643D091A14,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,https://instagram.fgua5-1.fna.fbcdn.net/v/t50....,True,1761.0,viajaconorus,ORUS 🐶,2018-03-13 10:26:27,"['viajaconnosotrosgt', 'cachorro', 'mascota', ..."

In [77]:
col = ["username"]
data.loc[:,col] = data.loc[:, col].ffill()
data

,Unnamed: 0,csrf_token,viewer,viewer_id,country_code,language_code,locale,device_id,browser_push_pub_key,key_id,...,viewer_has_saved_to_collection,viewer_in_photo_of_you,viewer_can_reshare,video_url,has_audio,video_view_count,username,full_name,upload_date,hashtags
0,0,D6iS7WnSFbhB9ZUFt5nWK51xdDegcZ6V,NaN,NaN,GT,en,en_US,D4425F91-940E-4EE7-8FAA-4E1AAA1A8B58,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-21 09:22:24,[]
1,1,n9cW3xMiT311ZhtAfXYnEYO9dRBGkbhE,NaN,NaN,GT,en,en_US,D4EBBE02-4EF2-46E4-ACA7-4F8908A0C0AF,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-20 09:32:18,[]
2,2,Y5WDcpqc8y0rsED1yI8YciJSgEqLJ9bT,NaN,NaN,GT,en,en_US,251B69CB-92EE-4D3A-B536-72AD356D98D8,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-16 09:28:28,['dogapproved']
3,3,5vFgXtmB2ihqowxoeLeVKvWA8UrpxAsa,NaN,NaN,GT,en,en_US,A0334128-ADCC-4A0F-8FD9-F27024D2BC57,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-13 14:57:03,"['OliyBu', 'ThiagoyBu', 'OliThiagoyBu']"
4,4,F4ejlkqj0IhfwjCDxNAdffQCjBci05NN,NaN,NaN,GT,en,en_US,4C162E02-7158-4F01-AE88-7A3FC33167EE,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-07 11:44:15,"['christmaspresent', 'bestchristmaspresent', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,282,n4Op0SpSdON8Alm73sklKsFtMSFajndb,NaN,NaN,GT,en,en_US,24F51DB7-3445-4134-840A-7F192ACEABC1,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,viajaconorus,ORUS 🐶,2018-03-19 20:45:33,"['viajaconnosotrosgt', 'mascota', 'perrito', '..."
283,283,oA6HHMM4mtARcUGfY1t1bbDNc81Q5t11,NaN,NaN,GT,en,en_US,B78146C2-D168-4D90-B0A6-EAA209EC5F62,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,viajaconorus,ORUS 🐶,2018-03-17 11:30:10,"['viajaconnosotrosgt', 'mascota', 'cachorro', ..."
284,284,Teg45mwLe9IFd9PpUI5eANuxJ4apJ6ii,NaN,NaN,GT,en,en_US,62F229B7-FC8B-4252-8C15-6BA598AFA910,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,viajaconorus,ORUS 🐶,2018-03-15 09:53:09,"['viajaconnosotrosgt', 'viajero', 'playa', 'ma..."
285,285,j5KK3RgXxlVqWCx26IuPndKI6lUOixw2,NaN,NaN,GT,en,en_US,8B45189C-6935-46D6-B4E2-4C3F994665B5,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,viajaconorus,ORUS 🐶,2018-03-14 13:16:33,"['viajaconnosotrosgt', 'instadog', 'instaguate..."
286,286,RaCqworpc7ms10NX7mVJHSDvLf1egd8R,NaN,NaN,GT,en,en_US,2CB5958D-4D52-4F66-A15D-8D643D091A14,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,https://instagram.fgua5-1.fna.fbcdn.net/v/t50....,True,1761.0,viajaconorus,ORUS 🐶,2018-03-13 10:26:27,"['viajaconnosotrosgt', 'cachorro', 'mascota', ..."

La columna _upload_date_ indica la fecha en que el _post_ fué publicado. Convierta el campo *upload_data* a *date_time*.  Puede utilizar el método to_datetime() de pandas.

In [78]:
data["upload_date"] = pd.to_datetime(data["upload_date"])

Utilice esta columna para descartar los datos del 25 de diciembre 2020 en adelante.

In [79]:
#Descarte la data >= '2020-12-25'
data = data[data.upload_date < '25/12/2020']

## Antes de comenzar a analizar los datos entienda la estructura de los datos

Utilice el método info() y analize la estructura y tipos de datos del DataFrame

In [80]:
pd.DataFrame.info(data)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2088 entries, 0 to 286
Data columns (total 52 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      2088 non-null   int64
 1   csrf_token                      2088 non-null   object
 2   viewer                          0 non-null      float64
 3   viewer_id                       0 non-null      float64
 4   country_code                    2088 non-null   object
 5   language_code                   2088 non-null   object
 6   locale                          2088 non-null   object
 7   device_id                       2088 non-null   object
 8   browser_push_pub_key            2088 non-null   object
 9   key_id                          2088 non-null   int64
 10  public_key                      2088 non-null   object
 11  version                         2088 non-null   int64
 12  is_dev                          2088 non-null   bool
 13  rollout_hash                    2088 non-null   object
 14  bundle_variant                  2088 non-null   object
 15  frontend_dev                    2088 non-null   object
 16  id                              2088 non-null   int64
 17  shortcode                       2088 non-null   object
 18  height                          2088 non-null   int64
 19  width                           2088 non-null   int64
 20  gating_info                     0 non-null      float64
 21  fact_check_overall_rating       0 non-null      float64
 22  fact_check_information          0 non-null      float64
 23  sensitivity_friction_info       0 non-null      float64
 24  media_overlay_info              0 non-null      float64
 25  media_preview                   1480 non-null   object
 26  display_url                     2088 non-null   object
 27  accessibility_caption           1928 non-null   object
 28  is_video                        2088 non-null   bool
 29  tracking_token                  2088 non-null   object
 30  tagged_users                    2088 non-null   object
 31  caption                         2088 non-null   object
 32  caption_is_edited               2088 non-null   bool
 33  has_ranked_comments             2088 non-null   bool
 34  comments                        2088 non-null   int64
 35  comments_disabled               2088 non-null   bool
 36  commenting_disabled_for_viewer  2088 non-null   bool
 37  timestamp                       2088 non-null   int64
 38  likes                           2088 non-null   int64
 39  location                        1162 non-null   object
 40  viewer_has_liked                2088 non-null   bool
 41  viewer_has_saved                2088 non-null   bool
 42  viewer_has_saved_to_collection  2088 non-null   bool
 43  viewer_in_photo_of_you          2088 non-null   bool
 44  viewer_can_reshare              2088 non-null   bool
 45  video_url                       231 non-null    object
 46  has_audio                       231 non-null    object
 47  video_view_count                231 non-null    float64
 48  username                        2088 non-null   object
 49  full_name                       2088 non-null   object
 50  upload_date                     2088 non-null   datetime64[ns]
 51  hashtags                        2088 non-null   object
dtypes: bool(11), datetime64[ns](1), float64(8), int64(9), object(23)
memory usage: 707.6+ KB

Utilice el método head() para tener una idea de la información contenida en cada columna

In [81]:
data.head()

,Unnamed: 0,csrf_token,viewer,viewer_id,country_code,language_code,locale,device_id,browser_push_pub_key,key_id,...,viewer_has_saved_to_collection,viewer_in_photo_of_you,viewer_can_reshare,video_url,has_audio,video_view_count,username,full_name,upload_date,hashtags
0,0,D6iS7WnSFbhB9ZUFt5nWK51xdDegcZ6V,NaN,NaN,GT,en,en_US,D4425F91-940E-4EE7-8FAA-4E1AAA1A8B58,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-21 09:22:24,[]
1,1,n9cW3xMiT311ZhtAfXYnEYO9dRBGkbhE,NaN,NaN,GT,en,en_US,D4EBBE02-4EF2-46E4-ACA7-4F8908A0C0AF,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-20 09:32:18,[]
2,2,Y5WDcpqc8y0rsED1yI8YciJSgEqLJ9bT,NaN,NaN,GT,en,en_US,251B69CB-92EE-4D3A-B536-72AD356D98D8,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-16 09:28:28,['dogapproved']
3,3,5vFgXtmB2ihqowxoeLeVKvWA8UrpxAsa,NaN,NaN,GT,en,en_US,A0334128-ADCC-4A0F-8FD9-F27024D2BC57,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-13 14:57:03,"['OliyBu', 'ThiagoyBu', 'OliThiagoyBu']"
4,4,F4ejlkqj0IhfwjCDxNAdffQCjBci05NN,NaN,NaN,GT,en,en_US,4C162E02-7158-4F01-AE88-7A3FC33167EE,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-07 11:44:15,"['christmaspresent', 'bestchristmaspresent', '..."

## Cuál es la cuenta con mas publicaciones?
El campo _id_ es un identificador único para cada _post_ . Utilizando groupby() cree una tabla mostrando la cantidad de _posts_ para cada _username_.  Esta tabla debe tener 3 columnas: _full_name_, _username_ y el recuento de _id_

In [87]:
data.groupby(["full_name","username"])["id"].count().to_frame().sort_values(by = "id", ascending = False)

                                              id
full_name              username
Bu the Westie          buthewestie           611
Lilo                   kimpugdashian         591
Guatemala Pet Friendly guatemalapetfriendly  360
ORUS 🐶                 viajaconorus          286
Potter_el_labrador 🇬🇹  potter_cm             240

## Cúal es la cuenta del post más antiguo y del más reciente?

Encuentre el _id_ del _post_ más antiguo e indique a que _username_ pertenece. Debe mostrar estos 3 datos únicamente: _id_, _username_, _upload_date_.

In [117]:
publi = data[["id", "username","upload_date"]]
publi[publi["upload_date"]==publi["upload_date"].min()]

                      id     username         upload_date
610  1110533568476282948  buthewestie 2015-11-03 20:58:59

Encuentre el _id_ del _post_ más reciente e indique a que _username_ pertenece. Debe mostrar estos 3 datos únicamente: _id_, _username_, _upload_date_

In [118]:
publi[publi["upload_date"]==publi["upload_date"].max()]

                    id      username         upload_date
1  2471633081865386102  viajaconorus 2020-12-24 20:00:45

## La cuenta con mas likes

La columna _likes_ indica la cantidad de _likes_ en cada _post_. Utilizando groupby() cree una tabla mostrando la cantidad de _likes_ para cada _username_. Indique en el comentario el _username_ de la cuenta con la mayor y la menor cantidad de _likes_,  también indique la cantidad de _likes_.

In [121]:
# la cuenta con mas likes es viajaconorus con 163,299 likes
# la cuenta con menos likes es potter_cm con 13,988 likes

data.groupby(["username"])["likes"].sum().to_frame().sort_values(by = "likes", ascending = False)

                       likes
username
viajaconorus          163299
buthewestie           139609
kimpugdashian          77701
guatemalapetfriendly   32387
potter_cm              13988

## Publicar vídeos ayuda a tener likes?

La columna _is_video_ nos dice dice si el _post_ es un vídeo. Utilizando groupby() cree una tabla mostrando la cantidad de vídeos para cada _username_ y compare si la cuenta con más vídeos es la cuenta con más _likes_.

In [125]:
data.groupby(["username", "is_video"])["likes"].sum().to_frame().sort_values(by = "likes", ascending = False)

                                likes
username             is_video
viajaconorus         False     157283
buthewestie          False     136228
kimpugdashian        False      73674
guatemalapetfriendly False      30438
potter_cm            False      12266
viajaconorus         True        6016
kimpugdashian        True        4027
buthewestie          True        3381
guatemalapetfriendly True        1949
potter_cm            True        1722

Ve una relación entre la cantidad de likes y la cantidad de vídeos publicados? Indique su respuesta en un comentario en la celda a continuación.

In [ ]:
# Indique su respuesta acá
#En su mayoría, subir videos ayuda a tener más likes, existe un único caso en el que esto no es cierto.
#Por ejemplo la persona en segundo lugar de likes, se encuentra en tercer lugar al subir videos

## El mejor día de la semana para publicar basado en likes

Cree una tabla que muestre el promedio de likes por _post_ para cada día de la semana (lun, mar, mie, jue, vie, sab, dom). 

### Referencia
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.day_name.html?highlight=day_name

In [154]:
data["WeekDay"] = data['upload_date'].dt.day_name()
data.head()

,Unnamed: 0,csrf_token,viewer,viewer_id,country_code,language_code,locale,device_id,browser_push_pub_key,key_id,...,viewer_in_photo_of_you,viewer_can_reshare,video_url,has_audio,video_view_count,username,full_name,upload_date,hashtags,WeekDay
upload_date,,,,,,,,,,,,,,,,,,,,,
2020-12-21 09:22:24,0,D6iS7WnSFbhB9ZUFt5nWK51xdDegcZ6V,NaN,NaN,GT,en,en_US,D4425F91-940E-4EE7-8FAA-4E1AAA1A8B58,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-21 09:22:24,[],Monday
2020-12-20 09:32:18,1,n9cW3xMiT311ZhtAfXYnEYO9dRBGkbhE,NaN,NaN,GT,en,en_US,D4EBBE02-4EF2-46E4-ACA7-4F8908A0C0AF,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-20 09:32:18,[],Sunday
2020-12-16 09:28:28,2,Y5WDcpqc8y0rsED1yI8YciJSgEqLJ9bT,NaN,NaN,GT,en,en_US,251B69CB-92EE-4D3A-B536-72AD356D98D8,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-16 09:28:28,['dogapproved'],Wednesday
2020-12-13 14:57:03,3,5vFgXtmB2ihqowxoeLeVKvWA8UrpxAsa,NaN,NaN,GT,en,en_US,A0334128-ADCC-4A0F-8FD9-F27024D2BC57,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-13 14:57:03,"['OliyBu', 'ThiagoyBu', 'OliThiagoyBu']",Sunday
2020-12-07 11:44:15,4,F4ejlkqj0IhfwjCDxNAdffQCjBci05NN,NaN,NaN,GT,en,en_US,4C162E02-7158-4F01-AE88-7A3FC33167EE,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,False,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-07 11:44:15,"['christmaspresent', 'bestchristmaspresent', '...",Monday

In [157]:
data.groupby(["WeekDay"])["likes"].mean().to_frame().sort_values(by = "likes", ascending = False)

                likes
WeekDay
Tuesday    222.523132
Wednesday  212.922601
Friday     208.466667
Thursday   206.710526
Sunday     205.368116
Monday     199.332155
Saturday   172.902622

Cuál es el día con más likes promedio por _post_?  Indique su respuesta en un comentario en la celda a continuación.

In [ ]:
# El día con mas likes promedio por post es: martes con 222 likes por publicación

## Agregar una ubicación a la publicación aumenta la cantidad de _likes_?

La columna _location_ nos dice la ubicación que se le asignó al _post_. Este es un parámetro opcional al momento de publicar. Cree una tabla que permita analizar si agregar una ubicación a la publicación ayuda a tener mas likes. La tabla debe tener las siguientes 2 columnas: _Flag_ indicando si el _post_ tiene o no tiene ubicación indicada, promedio de likes por _post_

In [174]:
data["Flag"] = data["location"].apply(lambda x: "No" if pd.isnull(x)  else "Si")
data.head()

,Unnamed: 0,csrf_token,viewer,viewer_id,country_code,language_code,locale,device_id,browser_push_pub_key,key_id,...,viewer_can_reshare,video_url,has_audio,video_view_count,username,full_name,upload_date,hashtags,WeekDay,Flag
upload_date,,,,,,,,,,,,,,,,,,,,,
2020-12-21 09:22:24,0,D6iS7WnSFbhB9ZUFt5nWK51xdDegcZ6V,NaN,NaN,GT,en,en_US,D4425F91-940E-4EE7-8FAA-4E1AAA1A8B58,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-21 09:22:24,[],Monday,Si
2020-12-20 09:32:18,1,n9cW3xMiT311ZhtAfXYnEYO9dRBGkbhE,NaN,NaN,GT,en,en_US,D4EBBE02-4EF2-46E4-ACA7-4F8908A0C0AF,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-20 09:32:18,[],Sunday,Si
2020-12-16 09:28:28,2,Y5WDcpqc8y0rsED1yI8YciJSgEqLJ9bT,NaN,NaN,GT,en,en_US,251B69CB-92EE-4D3A-B536-72AD356D98D8,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-16 09:28:28,['dogapproved'],Wednesday,Si
2020-12-13 14:57:03,3,5vFgXtmB2ihqowxoeLeVKvWA8UrpxAsa,NaN,NaN,GT,en,en_US,A0334128-ADCC-4A0F-8FD9-F27024D2BC57,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-13 14:57:03,"['OliyBu', 'ThiagoyBu', 'OliThiagoyBu']",Sunday,No
2020-12-07 11:44:15,4,F4ejlkqj0IhfwjCDxNAdffQCjBci05NN,NaN,NaN,GT,en,en_US,4C162E02-7158-4F01-AE88-7A3FC33167EE,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,True,NaN,NaN,NaN,buthewestie,Bu the Westie,2020-12-07 11:44:15,"['christmaspresent', 'bestchristmaspresent', '...",Monday,Si

In [175]:
data.groupby(["Flag"])["likes"].mean().to_frame().sort_values(by = "likes", ascending = False)

           likes
Flag
Si    282.979346
No    106.006479

Basado en su análisis anterior, sería válido asumir que indicar la ubicación ayuda a tener más likes? Indique su respuesta en un comentario en la celda a continuación.

In [ ]:
# Es válido asumir que indicar la ubicación ayuda a tener más likes?: Si es valida esta suposición 
# Los datos muestran que en promedio se obtienen 283 likes al agregar una ubicación vs los 106 al no hacerlo

## La cantidad de caracteres en la descipción de la publicación ayuda a tener más likes?

La columna _caption_ es la descipción que se publicón con el _post_. Calcule la cantidad de caracteres de esta columna y luego y asignelo a una nueva columna llamada _caption_length_. Luego cree una segunda columna llamada _caption_length_bins_ categorice la cantidad de caracteres en rangos, usted decide el tamaño de cada rango. Por último cree una tabla que permita analizar si a mayor cantidad de caracteres en la descipción es mayor la cantidad de likes por post.

### Referencia
* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.len.html?highlight=len
* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html

In [178]:
data["caption_length"] = data["caption"].str.len()
data["caption_length_bins"] = data["caption_length"].apply(lambda x: "< 100" if x <100
                                                           else ("< 200" if x < 200 
                                                                else ("< 400" if x < 400
                                                                     else ("< 600" if x < 600 else "+ 600"))))
data.head()

,Unnamed: 0,csrf_token,viewer,viewer_id,country_code,language_code,locale,device_id,browser_push_pub_key,key_id,...,has_audio,video_view_count,username,full_name,upload_date,hashtags,WeekDay,Flag,caption_length,caption_length_bins
upload_date,,,,,,,,,,,,,,,,,,,,,
2020-12-21 09:22:24,0,D6iS7WnSFbhB9ZUFt5nWK51xdDegcZ6V,NaN,NaN,GT,en,en_US,D4425F91-940E-4EE7-8FAA-4E1AAA1A8B58,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,NaN,NaN,buthewestie,Bu the Westie,2020-12-21 09:22:24,[],Monday,Si,217,< 400
2020-12-20 09:32:18,1,n9cW3xMiT311ZhtAfXYnEYO9dRBGkbhE,NaN,NaN,GT,en,en_US,D4EBBE02-4EF2-46E4-ACA7-4F8908A0C0AF,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,NaN,NaN,buthewestie,Bu the Westie,2020-12-20 09:32:18,[],Sunday,Si,197,< 200
2020-12-16 09:28:28,2,Y5WDcpqc8y0rsED1yI8YciJSgEqLJ9bT,NaN,NaN,GT,en,en_US,251B69CB-92EE-4D3A-B536-72AD356D98D8,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,NaN,NaN,buthewestie,Bu the Westie,2020-12-16 09:28:28,['dogapproved'],Wednesday,Si,463,< 600
2020-12-13 14:57:03,3,5vFgXtmB2ihqowxoeLeVKvWA8UrpxAsa,NaN,NaN,GT,en,en_US,A0334128-ADCC-4A0F-8FD9-F27024D2BC57,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,NaN,NaN,buthewestie,Bu the Westie,2020-12-13 14:57:03,"['OliyBu', 'ThiagoyBu', 'OliThiagoyBu']",Sunday,No,110,< 200
2020-12-07 11:44:15,4,F4ejlkqj0IhfwjCDxNAdffQCjBci05NN,NaN,NaN,GT,en,en_US,4C162E02-7158-4F01-AE88-7A3FC33167EE,BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjF...,88,...,NaN,NaN,buthewestie,Bu the Westie,2020-12-07 11:44:15,"['christmaspresent', 'bestchristmaspresent', '...",Monday,Si,123,< 200

In [180]:
data.groupby(["caption_length_bins"])["likes"].sum().to_frame().sort_values(by = "likes", ascending = False)

                      likes
caption_length_bins
< 400                200412
< 600                101421
< 200                 50453
< 100                 43624
+ 600                 31074

Observa alguna relación entre la cantidad de likes y la longitud de la descripción? Indique su respuesta en un comentario en la celda a continuación.

In [ ]:
# Observa alguna relación entre la cantidad de likes y la longitud de la descripción?
# No existe una relación entre la cantidad de likes y la longitud, según se ve en promedio la gente lee más aquellos posts
# que están entre 300 y 400 caracteres, es decir, aproximadamente la media de los posts.
# Como se observa, las publicaciones con más caracteres son las menos aceptadas.